#!/usr/bin/env python3
"""Writes the core's OpenGL ES 2 shaders out as a C header.

Usage: gles2_shaders.py path/to/core/rend/gles/gles.cpp > gles2_shaders.h

gles2_test.c compiles and draws with the shaders the core itself uses, not
copies of them. They live in gles.cpp as printf formats; this fills them in
the way the core does for an OpenGL ES 2 context and a fogged, untextured,
Gouraud-shaded polygon.
"""
import re
import sys


def raw(source, name):
    m = re.search(name + r'\s*=\s*\n?R"\((.*?)\)";', source, flags=re.S)
    if not m:
        sys.exit('no %s in the source' % name)
    return m.group(1)


def fill(fmt, args):
    it = iter(args)
    return re.sub(r'%[sd]', lambda m: str(next(it)), fmt)


def literal(name, text):
    lines = ['static const char %s[] =' % name]
    for line in text.split('\n'):
        lines.append('   "%s\\n"' % line.replace('\\', '\\\\').replace('"', '\\"'))
    return '\n'.join(lines) + ';\n'


def main():
    source = open(sys.argv[1]).read()
    # version header, target, pp_Gouraud
    vertex = fill(raw(source, 'VertexShaderSource'), ['', 'GLES2', 1])
    # version header, target, cp_AlphaTest, pp_ClipInside, pp_UseAlpha,
    # pp_Texture, pp_IgnoreTexA, pp_ShadInstr, pp_Offset, pp_FogCtrl,
    # pp_Gouraud, pp_BumpMap, FogClamping, pp_TriLinear, pp_Palette
    fragment = fill(raw(source, 'PixelPipelineShader'),
                    ['', 'GLES2', 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0])
    sys.stdout.write('/* Generated by gles2_shaders.py from gles.cpp. */\n')
    sys.stdout.write(literal('vertex_source', vertex))
    sys.stdout.write(literal('fragment_source', fragment))


if __name__ == '__main__':
    main()
